// Generated by gencpp from file roboclaw_ros/roboclaw_service.msg
// DO NOT EDIT!


#ifndef ROBOCLAW_ROS_MESSAGE_ROBOCLAW_SERVICE_H
#define ROBOCLAW_ROS_MESSAGE_ROBOCLAW_SERVICE_H

#include <ros/service_traits.h>


#include <roboclaw_ros/roboclaw_serviceRequest.h>
#include <roboclaw_ros/roboclaw_serviceResponse.h>


namespace roboclaw_ros
{

struct roboclaw_service
{

typedef roboclaw_serviceRequest Request;
typedef roboclaw_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct roboclaw_service
} // namespace roboclaw_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboclaw_ros::roboclaw_service > {
  static const char* value()
  {
    return "9e36e203987fc6183576e3695ee8044e";
  }

  static const char* value(const ::roboclaw_ros::roboclaw_service&) { return value(); }
};

template<>
struct DataType< ::roboclaw_ros::roboclaw_service > {
  static const char* value()
  {
    return "roboclaw_ros/roboclaw_service";
  }

  static const char* value(const ::roboclaw_ros::roboclaw_service&) { return value(); }
};


// service_traits::MD5Sum< ::roboclaw_ros::roboclaw_serviceRequest> should match 
// service_traits::MD5Sum< ::roboclaw_ros::roboclaw_service > 
template<>
struct MD5Sum< ::roboclaw_ros::roboclaw_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboclaw_ros::roboclaw_service >::value();
  }
  static const char* value(const ::roboclaw_ros::roboclaw_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboclaw_ros::roboclaw_serviceRequest> should match 
// service_traits::DataType< ::roboclaw_ros::roboclaw_service > 
template<>
struct DataType< ::roboclaw_ros::roboclaw_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::roboclaw_ros::roboclaw_service >::value();
  }
  static const char* value(const ::roboclaw_ros::roboclaw_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboclaw_ros::roboclaw_serviceResponse> should match 
// service_traits::MD5Sum< ::roboclaw_ros::roboclaw_service > 
template<>
struct MD5Sum< ::roboclaw_ros::roboclaw_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboclaw_ros::roboclaw_service >::value();
  }
  static const char* value(const ::roboclaw_ros::roboclaw_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboclaw_ros::roboclaw_serviceResponse> should match 
// service_traits::DataType< ::roboclaw_ros::roboclaw_service > 
template<>
struct DataType< ::roboclaw_ros::roboclaw_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::roboclaw_ros::roboclaw_service >::value();
  }
  static const char* value(const ::roboclaw_ros::roboclaw_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOCLAW_ROS_MESSAGE_ROBOCLAW_SERVICE_H
