// Generated by gencpp from file beginner_tutorials/roboclaw_service.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ROBOCLAW_SERVICE_H
#define BEGINNER_TUTORIALS_MESSAGE_ROBOCLAW_SERVICE_H

#include <ros/service_traits.h>


#include <beginner_tutorials/roboclaw_serviceRequest.h>
#include <beginner_tutorials/roboclaw_serviceResponse.h>


namespace beginner_tutorials
{

struct roboclaw_service
{

typedef roboclaw_serviceRequest Request;
typedef roboclaw_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct roboclaw_service
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::roboclaw_service > {
  static const char* value()
  {
    return "9e36e203987fc6183576e3695ee8044e";
  }

  static const char* value(const ::beginner_tutorials::roboclaw_service&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::roboclaw_service > {
  static const char* value()
  {
    return "beginner_tutorials/roboclaw_service";
  }

  static const char* value(const ::beginner_tutorials::roboclaw_service&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::roboclaw_serviceRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::roboclaw_service > 
template<>
struct MD5Sum< ::beginner_tutorials::roboclaw_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::roboclaw_service >::value();
  }
  static const char* value(const ::beginner_tutorials::roboclaw_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::roboclaw_serviceRequest> should match 
// service_traits::DataType< ::beginner_tutorials::roboclaw_service > 
template<>
struct DataType< ::beginner_tutorials::roboclaw_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::roboclaw_service >::value();
  }
  static const char* value(const ::beginner_tutorials::roboclaw_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::roboclaw_serviceResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::roboclaw_service > 
template<>
struct MD5Sum< ::beginner_tutorials::roboclaw_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::roboclaw_service >::value();
  }
  static const char* value(const ::beginner_tutorials::roboclaw_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::roboclaw_serviceResponse> should match 
// service_traits::DataType< ::beginner_tutorials::roboclaw_service > 
template<>
struct DataType< ::beginner_tutorials::roboclaw_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::roboclaw_service >::value();
  }
  static const char* value(const ::beginner_tutorials::roboclaw_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ROBOCLAW_SERVICE_H
