// Generated by gencpp from file roboclaw_ros/roboclaw_serviceRequest.msg
// DO NOT EDIT!


#ifndef ROBOCLAW_ROS_MESSAGE_ROBOCLAW_SERVICEREQUEST_H
#define ROBOCLAW_ROS_MESSAGE_ROBOCLAW_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboclaw_ros
{
template <class ContainerAllocator>
struct roboclaw_serviceRequest_
{
  typedef roboclaw_serviceRequest_<ContainerAllocator> Type;

  roboclaw_serviceRequest_()
    : enc(0)  {
    }
  roboclaw_serviceRequest_(const ContainerAllocator& _alloc)
    : enc(0)  {
  (void)_alloc;
    }



   typedef int64_t _enc_type;
  _enc_type enc;




  typedef boost::shared_ptr< ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct roboclaw_serviceRequest_

typedef ::roboclaw_ros::roboclaw_serviceRequest_<std::allocator<void> > roboclaw_serviceRequest;

typedef boost::shared_ptr< ::roboclaw_ros::roboclaw_serviceRequest > roboclaw_serviceRequestPtr;
typedef boost::shared_ptr< ::roboclaw_ros::roboclaw_serviceRequest const> roboclaw_serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboclaw_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f17c4e7ccff9c107a904bb75cbb99c36";
  }

  static const char* value(const ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf17c4e7ccff9c107ULL;
  static const uint64_t static_value2 = 0xa904bb75cbb99c36ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboclaw_ros/roboclaw_serviceRequest";
  }

  static const char* value(const ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 enc\n\
";
  }

  static const char* value(const ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct roboclaw_serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboclaw_ros::roboclaw_serviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "enc: ";
    Printer<int64_t>::stream(s, indent + "  ", v.enc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCLAW_ROS_MESSAGE_ROBOCLAW_SERVICEREQUEST_H
